### ISSUE TITLE
Broken authorization

### ISSUE THREAD

**Issue by spajic** [Absolventa/emarsys-rb#13]
This commit: https://github.com/Absolventa/emarsys-rb/pull/9 breaks authorization for me.
I get Emarsys::Unauthorized: HTTP-Code: 401, Emarsys-Code: 1 - Unauthorized Time frame is invalid

Does it work for anyone? What's the point?

**Comment by felin-arch** [comment]
@spajic, this PR fixed a security issue in the library, namely nonce reuse. See [the official documentation](https://documentation.emarsys.com/resource/developers/getting-started/authentication/) for more details on this. As for the timeframe issue, you are receiving this error because the Date you use to calculate the signature is not within 5 minutes of the actual time.

Emarsys servers return the Date in their response headers, so you can use that to check time your signature is compared against. 

Free to contact your Emarsys representative as they will surely be able to help!

**Comment by spajic** [comment]
@felin-arch Thank you! I'll check it out.

**Comment by mungler** [comment]
Fixed as of PR #19
